# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberForList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NumberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField(auto_created=True)),
            ],
        ),
        migrations.AddField(
            model_name='numberforlist',
            name='number_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlgorithmViewer.NumberList'),
        ),
    ]
